# Chipotle Catering Order Optimization

In [62]:
import cvxpy as cp
import numpy as np

P = cp.Variable((30, 7), boolean = True)  # protein choice selection
R = cp.Variable((30, 2), boolean = True)  # rice choice selection
B = cp.Variable((30, 2), boolean = True)  # beans choice selection
T = cp.Variable((30, 10), boolean = True) # toppings selection
L = cp.Variable((30, 1), boolean = True)  # extra tortilla selection
C = cp.Variable((30, 1), boolean = True)  # chips selection
Y = cp.Variable(2, boolean = True) #for if then constraint

n,m=P.shape  #MAY BE USEFUL WHEN CREATING CONSTRAINTS + SEE VERY BOTTOM

CP=np.array([[11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4],
            [11.4, 8.4, 10.15, 10.15, 9.05, 8.4, 8.4]]) # cost of protein choice

CT=np.array([[2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4],
             [2.5, 0, 0, 0, 0, 0, 0, 0, 0, 1.4]])          # cost of additional toppings

CL=np.array([[0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50],
            [0.50]])         # cost of additional tortilla

CC=np.array([[1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65],
            [1.65]])         # cost of chips

P.protein = np.array([[29,32,21,24,23,8,2]])
R.protein = np.array([[4,4]])
B.protein = np.array([[8,8]])
T.protein = np.array([[2,0,3,0,0,2,1,6,0,5]])                         # grams of protein in each ingredient
L.protein = np.array([[8]])
C.protein = np.array([[7]])

P.fat = np.array([[14,7,6,7,12,10,22]])
R.fat = np.array([[4,6]])
B.fat = np.array([[2,2]])
T.fat = np.array([[22,0,2,0,0,9,0,8,0,9]])                            # grams of fat in each ingredient
L.fat = np.array([[9]])
C.fat = np.array([[25]])

P.carbs = np.array([[1,0,1,2,0,9,0,8]])
R.carbs = np.array([[40,36]])
B.carbs = np.array([[22,21]])
T.carbs = np.array([[8,4,16,4,4,2,5,1,1,4]])                          # grams of carbs in each ingredient
L.carbs = np.array([[50]])
C.carbs = np.array([[73]])

P.calories = np.array([[250,180,150,170,210,150,230]])
R.calories = np.array([[210,210]])
B.calories = np.array([[130,130]])
T.calories = np.array([[230,25,80,15,30,110,20,110,5,120]])           # calories in each ingredient
L.calories = np.array([[320]])
C.calories = np.array([[540]])

obj_func = cp.trace(CP.T @ P) + cp.trace(CT.T @ T) + cp.trace(CL.T @ L) + cp.trace(CC.T @ C)

constraints = []

# Protein Constraints (Protein>=22 (30 but 8 accounted for by tortilla))
for i in range(n):
    protein_protein = 0
    rice_protein = 0
    beans_protein = 0
    toppings_protein = 0
    extra_tort_protein = 0
    chips_protein = 0
    for j in range(m):
        protein_protein += P[i, j]*P.protein[0,j]
    for r in range(R.shape[1]):
        rice_protein += R[i, r]*R.protein[0,r]
        beans_protein += B[i, r]*B.protein[0,r]
    for t in range(T.shape[1]):
        toppings_protein += T[i, t]*T.protein[0,t]
    extra_tort_protein = L[i, 0]*L.protein[0,0]
    chips_protein = C[i, 0]*C.protein[0,0]
    constraints.append(protein_protein + rice_protein + beans_protein + toppings_protein + extra_tort_protein + chips_protein >= 22)
# Fat Constraints (Fat>=21 (30 but 9 accounted for by tortilla))
for i in range(n):
    protein_fat = 0
    rice_fat = 0
    beans_fat = 0
    toppings_fat = 0
    extra_tort_fat = 0
    chips_fat = 0
    for j in range(m):
        protein_fat += P[i, j]*P.fat[0,j]
    for r in range(R.shape[1]):
        rice_fat += R[i, r]*R.fat[0,r]
        beans_fat += B[i, r]*B.fat[0,r]
    for t in range(T.shape[1]):
        toppings_fat += T[i, t]*T.fat[0,t]
    extra_tort_fat = L[i, 0]*L.fat[0,0]
    chips_fat = C[i, 0]*C.fat[0,0]
    constraints.append(protein_fat + rice_fat + beans_fat + toppings_fat + extra_tort_fat + chips_fat >= 21)
# Carb Constraints (Carb>=80 (130 but 50 accounted for by tortilla))
for i in range(n):
    protein_carbs = 0
    rice_carbs = 0
    beans_carbs = 0
    toppings_carbs = 0
    extra_tort_carbs = 0
    chips_carbs = 0
    for j in range(m):
        protein_carbs += P[i, j]*P.carbs[0,j]
    for r in range(R.shape[1]):
        rice_carbs += R[i, r]*R.carbs[0,r]
        beans_carbs += B[i, r]*B.carbs[0,r]
    for t in range(T.shape[1]):
        toppings_carbs += T[i, t]*T.carbs[0,t]
    extra_tort_carbs = L[i, 0]*L.carbs[0,0]
    chips_carbs = C[i, 0]*C.carbs[0,0]
    constraints.append(protein_carbs + rice_carbs + beans_carbs + toppings_carbs + extra_tort_carbs + chips_carbs >= 80)
# Calorie Constraints (Cal>=680 (1000 but 320 accounted for by tortilla))
for i in range(n):
    protein_calories = 0
    rice_calories = 0
    beans_calories = 0
    toppings_calories = 0
    extra_tort_calories = 0
    chips_calories = 0
    for j in range(m):
        protein_calories += P[i, j]*P.calories[0,j]
    for r in range(R.shape[1]):
        rice_calories += R[i, r]*R.calories[0,r]
        beans_calories += B[i, r]*B.calories[0,r]
    for t in range(T.shape[1]):
        toppings_calories += T[i, t]*T.calories[0,t]
    extra_tort_calories = L[i, 0]*L.calories[0,0]
    chips_calories = C[i, 0]*C.calories[0,0]
    constraints.append(protein_calories + rice_calories + beans_calories + toppings_calories + extra_tort_calories + chips_calories >= 680)
    constraints.append(protein_calories + rice_calories + beans_calories + toppings_calories + extra_tort_calories + chips_calories <= 1180)
# Heavy Eater Calorie Constraints (Cal>=930 (1250 but 320 accounted for by tortilla))
for i in range(10):
    protein_heavy_calories = 0
    rice_heavy_calories = 0
    beans_heavy_calories = 0
    toppings_heavy_calories = 0
    extra_tort_heavy_calories = 0
    chips_heavy_calories = 0
    for j in range(m):
        protein_heavy_calories += P[i, j]*P.calories[0,j]
    for r in range(R.shape[1]):
        rice_heavy_calories += R[i, r]*R.calories[0,r]
        beans_heavy_calories += B[i, r]*B.calories[0,r]
    for t in range(T.shape[1]):
        toppings_heavy_calories += T[i, t]*T.calories[0,t]
    extra_tort_heavy_calories = L[i, 0]*L.calories[0,0]
    chips_heavy_calories = C[i, 0]*C.calories[0,0]
    constraints.append(protein_heavy_calories + rice_heavy_calories + beans_heavy_calories + toppings_heavy_calories + extra_tort_heavy_calories + chips_heavy_calories >= 930)
# Protein Constraints (P_1,1 + P_1,2 + ,..., + P_1,7 == 1)
for i in range(n):
    constraints.append(cp.sum(P[i,:])==1)
# Vegitarian Constraints (P_1,6 + P_1,7 + P_2,6 + P_2,7 + ,..., + P_30,6 + P_30,7 == 5)
total_veggies = 0
for i in range(n):
    total_veggies += P[i, 5] + P[i,6]
constraints.append(total_veggies == 5)
# Carne Asada Constraints (P_1,1 + P_2,1 + ... + P_30,1 == 5)
total_carne = 0
for i in range(n):
    total_carne += P[i, 0]
constraints.append(total_carne == 5)
# Choice of Rice Constraints (1 <= R_1,1 + R_1,2 <= 2  ,..., 1 <= R_30,1 + R_30,2 <= 2)
for i in range(n):
    constraints.append(R[i, 0] + R[i,1] <= 2)
    constraints.append(R[i, 0] + R[i,1] >= 1)
# Choice of Beans Constraints (1 <= B_1,1 + B_1,2 <= 2  ,..., 1 <= B_30,1 + B_30,2 <= 2)
for i in range(n):
    constraints.append(B[i, 0] + B[i,1] <= 2)
    constraints.append(B[i, 0] + B[i,1] >= 1)
# Choice of Toppings (T_1,1 <= 1,  T_1,2 <= 2 ,..., T_1,9 <= 2,  T_1,10 <=1)
#                    (Repeated for each individual + 1st & 10th topping has a limit of one (guac & queso respectively))
for i in range(n):
    constraints.append(T[i,0] <= 1)
    constraints.append(T[i,1] <= 2)
    constraints.append(T[i,2] <= 2)
    constraints.append(T[i,3] <= 2)
    constraints.append(T[i,4] <= 2)
    constraints.append(T[i,5] <= 2)
    constraints.append(T[i,6] <= 2)
    constraints.append(T[i,7] <= 2)
    constraints.append(T[i,8] <= 2)
    constraints.append(T[i,9] <= 1)    
# Salsa Constraints (1 <= T_1,2 + T_1,3 + T_1,4 + T_1,5 ,..., 1 <= T_30,2 + T_30,3 + T_30,4 + T_30,5)
for i in range(n):
    constraints.append(T[i,1] + T[i,2] + T[i,3] + T[i,4] >= 1)
# Constraint which restricts guacamole option when protein is selected as veggie (i.e. IF P_i,7 == 1, THEN T_i,1 == 0)
for i in range(n):
    constraints.append(P[i,6] == 1 + 100000*(Y))
    constraints.append(T[i,0] == 1 + 100000*(1-Y))

problem = cp.Problem(cp.Minimize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = False)
problem.solve(solver=cp.GUROBI,verbose = False)

print("obj_func =")
print(obj_func.value)
print("P = ")
print(np.round(P.value))
print("R = ")
print(np.round(R.value))
print("B = ")
print(np.round(B.value))
print("T = ")
print(np.round(T.value))
print("L = ")
print(np.round(L.value))
print("C = ")
print(np.round(C.value))

obj_func =
342.00000000000006
P = 
[[-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  1. -0. -0. -0. -0.  0.]
 [-0.  0.  0.  0.  0.  1.  0.]
 [-0.  0.  0.  0.  0.  1.  0.]
 [-0.  0.  0.  0.  0.  1.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.]
 [ 0.  1.  0.  0.  0. -0.  0.]
 [ 1.  0.  0.  0.  0. -0.  0.]
 [ 1.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0. -0.  0.]
 [ 1.  0.  0.  0.  0. -0.  0.]
 [ 1.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
R = 
[[ 1. -0.]
 [ 1. -0.]
 [ 1. -